#!/usr/bin/env python3
"""Generate lib/cards.ts from scripts/cards-resolved.json + downloaded files."""
from __future__ import annotations
import json
import os
import re

OUT = "lib/cards.ts"

with open("scripts/cards-resolved.json") as f:
    images = json.load(f)["images"]

def clean_title(t: str) -> str:
    # Strip leading punctuation / quotes
    t = t.strip(" '\"«»‘’“”")
    # Remove trailing image-id-looking junk: "WUS03292", "-DSC0123", "76e9", " B"
    t = re.sub(r"\b[A-Z]{2,4}\d{4,}\b", "", t)
    t = re.sub(r"-DSC\d+", "", t)
    t = re.sub(r"\b[a-z0-9]{4,8}\b$", "", t)  # trailing hash-looking blob
    # Strip year ranges like "(1816-1818)"
    t = re.sub(r"\(\s*\d{4}[\s\-–]*\d*\s*\)", "", t)
    # Collapse whitespace and trailing punctuation
    t = re.sub(r"\s+", " ", t).strip(" ,;-–—")
    # Remove "..." at end if it looks truncated mid-word
    if t.endswith("..."):
        t = t[:-3].rstrip(" -,")
    # Cap length
    if len(t) > 50:
        t = t[:47] + "…"
    # If empty after cleanup, fallback
    return t or "Untitled"

cards = []
for i, img in enumerate(images):
    # Pick the local file: whichever extension actually exists
    local = None
    for ext in (".jpg", ".jpeg", ".png"):
        path = f"public/cards/local-{i}{ext}"
        if os.path.exists(path):
            local = f"/cards/local-{i}{ext}"
            break
    if not local:
        print(f"WARNING: no local file for card {i}, skipping")
        continue
    # Wikimedia thumb URL — strip the analytics query params; they break clean URLs
    wikimedia = img["thumb"].split("?", 1)[0]
    title = clean_title(img["title"])
    cards.append({"id": i, "title": title, "wikimedia": wikimedia, "local": local})

# Sanity: we want exactly 100
print(f"Generated {len(cards)} cards")

# Emit TypeScript file
lines = [
    "// Auto-generated by scripts/generate_cards_ts.py — DO NOT EDIT BY HAND.",
    "// 100 public-domain artworks from Wikimedia Commons.",
    "// Each card has:",
    "//   - url: primary (Wikimedia CDN) — used first",
    "//   - localUrl: fallback (self-hosted in public/cards/) — used if Wikimedia fails",
    "",
    "export interface Card {",
    "  id: number;",
    "  url: string;",
    "  localUrl: string;",
    "  title: string;",
    "}",
    "",
    "export const CARDS: Card[] = [",
]
for c in cards:
    title_safe = c["title"].replace("\\", "\\\\").replace("'", "\\'")
    lines.append(
        f"  {{ id: {c['id']}, "
        f"url: '{c['wikimedia']}', "
        f"localUrl: '{c['local']}', "
        f"title: '{title_safe}' }},"
    )
lines.append("];")
lines.append("")
lines.append(f"export const CARD_COUNT = CARDS.length;")
lines.append("")

with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"Wrote {OUT}")
